name: $(SourceBranchName)-$(Date:yyyyMMdd).$(Rev:r)
variables:
  GOVER: '1.17.8'

trigger:
  batch: true
  branches:
    include: [ "master", "develop" ]
  paths:
    exclude: [ "README.md", "LICENSE", ".github/*", "examples/*", ".golangci.yml" ]

pr:
  autoCancel: true
  branches:
    include: [ "master", "develop" ]
  paths:
    exclude: [ "README.md", "LICENSE", ".github/*", "examples/*", ".golangci.yml" ]

jobs:
  - job: binary
    displayName: "binary build"
    pool:
      vmImage: "ubuntu-latest"
    workspace:
      clean: all
    timeoutInMinutes: 15

    steps:
      - task: GoTool@0
        displayName: 'Use Go'
        inputs:
          version: $(GOVER)

      - bash: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y upx
        displayName: 'Install Dependencies'

      - task: goreleaser@0
        inputs:
          version: 'latest'
          distribution: 'goreleaser'
          args: 'build --snapshot --rm-dist'
          workdir: '$(Build.SourcesDirectory)'

      - bash: |
          cp dist/* ${BUILD_ARTIFACTSTAGINGDIRECTORY}
        displayName: 'Copy Artifact'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        inputs:
          ArtifactName: 'snd'
